In [1]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [5]:
list(np.arange(.4 , 10.4 , 0.2)) #takes float also

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [7]:
np.linspace(1,5 , 20) 

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [8]:
np.logspace(1,5 , 10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [12]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
arr = np.ones((3,4))

In [15]:
arr


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [17]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [ ]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [18]:
arr1 = np.eye(5)

In [19]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
import pandas as pd

In [21]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [22]:
np.random.rand(2,3)

array([[0.71535374, 0.8971083 , 0.83956478],
       [0.12071878, 0.57501784, 0.20720551]])

In [23]:
np.random.randn(2,3)

array([[-0.15275861, -0.90461904,  1.31502238],
       [-0.44063793, -1.47369329,  0.71976918]])

In [24]:
arr2 = np.random.randint(1,5 , (3,4))

In [25]:
arr2

array([[2, 4, 1, 1],
       [1, 2, 1, 4],
       [1, 4, 1, 2]])

In [26]:
arr2.size

12

In [27]:
arr2.shape

(3, 4)

In [28]:
arr2.reshape(6,2)

array([[2, 4],
       [1, 1],
       [1, 2],
       [1, 4],
       [1, 4],
       [1, 2]])

In [29]:
arr2.reshape(2,6)

array([[2, 4, 1, 1, 1, 2],
       [1, 4, 1, 4, 1, 2]])

In [30]:
arr2.reshape(4,3)

array([[2, 4, 1],
       [1, 1, 2],
       [1, 4, 1],
       [4, 1, 2]])

In [31]:
arr2.reshape(4,-1)

array([[2, 4, 1],
       [1, 1, 2],
       [1, 4, 1],
       [4, 1, 2]])

In [32]:
arr2.reshape(4,-1432453453)

array([[2, 4, 1],
       [1, 1, 2],
       [1, 4, 1],
       [4, 1, 2]])

In [33]:
arr2.reshape(2,2,3,1,1,1)

array([[[[[[2]]],


         [[[4]]],


         [[[1]]]],



        [[[[1]]],


         [[[1]]],


         [[[2]]]]],




       [[[[[1]]],


         [[[4]]],


         [[[1]]]],



        [[[[4]]],


         [[[1]]],


         [[[2]]]]]])

In [34]:
arr1 = np.random.randint(1,10 , (5,6))

In [35]:
arr1

array([[1, 7, 2, 1, 7, 2],
       [9, 1, 4, 7, 7, 9],
       [2, 5, 8, 1, 7, 8],
       [8, 3, 3, 6, 4, 8],
       [7, 1, 1, 8, 5, 3]])

In [36]:
arr1 >8

array([[False, False, False, False, False, False],
       [ True, False, False, False, False,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [37]:
arr1[arr1 >8]

array([9, 9])

In [38]:
arr1

array([[1, 7, 2, 1, 7, 2],
       [9, 1, 4, 7, 7, 9],
       [2, 5, 8, 1, 7, 8],
       [8, 3, 3, 6, 4, 8],
       [7, 1, 1, 8, 5, 3]])

In [39]:
arr1[0,[0,1]]

array([1, 7])

In [40]:
arr1[2:4 , [2,3]]

array([[8, 1],
       [3, 6]])

In [41]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [42]:
arr1

array([[2, 2, 2],
       [1, 2, 1],
       [2, 2, 2]])

In [43]:
arr2

array([[1, 2, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [44]:
arr1+arr2


array([[3, 4, 3],
       [3, 3, 2],
       [4, 3, 4]])

In [45]:
arr1-arr2

array([[ 1,  0,  1],
       [-1,  1,  0],
       [ 0,  1,  0]])

In [46]:
arr1*arr2

array([[2, 4, 2],
       [2, 2, 1],
       [4, 2, 4]])

In [47]:
arr1

array([[2, 2, 2],
       [1, 2, 1],
       [2, 2, 2]])

In [48]:
arr2

array([[1, 2, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [49]:
arr1@arr2 #@ means matrix multiplication

array([[10,  8,  8],
       [ 7,  5,  5],
       [10,  8,  8]])

In [50]:
arr1/arr2

array([[2. , 1. , 2. ],
       [0.5, 2. , 1. ],
       [1. , 2. , 1. ]])

In [51]:
arr1/0

<ipython-input-51-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [52]:
#Numpy – Broadcasting.

In [53]:
arr = np.zeros((3,4))

In [54]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [56]:
a = np.array([1,2,3,4])

In [57]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [58]:
b = np.array([[3,4,5]])

In [61]:
arr1 = arr+b.T
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [62]:
b.T

array([[3],
       [4],
       [5]])

In [63]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [64]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [65]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [66]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [67]:
np.min(arr1)

3.0

In [68]:
np.max(arr1)

5.0