In [1]:
##Sort, Search & Counting Functions.

In [2]:
import numpy as np

In [3]:
arr = np.array([4,2,8,5,3,9,12,56])

In [4]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [5]:
np.sort(arr)

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [6]:
np.searchsorted(arr,6)

5

In [7]:
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])

In [8]:
np.count_nonzero(arr1)

6

In [9]:
np.where(arr1 > 0 )

(array([1, 2, 3, 4, 5, 9], dtype=int64),)

In [10]:
np.extract(arr1 >2,arr1)

array([324, 645,  65,   6,   6, 234])

In [11]:
#Numpy - Byte Swapping.

In [12]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [13]:
arr.byteswap(True)

array([ 67108864,  33554432, 134217728,  83886080,  50331648, 150994944,
       201326592, 939524096])

In [14]:
arr

array([ 67108864,  33554432, 134217728,  83886080,  50331648, 150994944,
       201326592, 939524096])

In [15]:
arr

array([ 67108864,  33554432, 134217728,  83886080,  50331648, 150994944,
       201326592, 939524096])

In [16]:
#Numpy - Copies &Views.

In [17]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [24]:
a = np.copy(arr1) #deep copy

In [25]:
b = arr1.view() #like a swallow copy

In [26]:
b

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [27]:
b[0] = 234

In [28]:
b

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [29]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [30]:
#Numpy - Matrix Library.

In [31]:
import numpy.matlib as nm

In [32]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [33]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [35]:
#Numpy - Linear Algebra

In [36]:
arr1 = np.random.randint([[2,3] , [4,5]])

In [37]:
arr2 = np.random.randint([[5,3] , [2,5]])


In [38]:
arr1

array([[1, 0],
       [1, 4]])

In [39]:
arr2

array([[1, 2],
       [1, 1]])

In [43]:
np.dot(arr1,arr2) #matrix multiplication

array([[1, 2],
       [5, 6]])

In [45]:
arr1@arr2 #matrix multiplication

array([[1, 2],
       [5, 6]])

In [47]:
np.flip(arr1)

array([[4, 1],
       [0, 1]])